function MFplotter(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 02-Mar-2022 15:01:13

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Color',[1 0 1]);

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XColor',[0 0 0],'XGrid','on','YAxisLocation','origin','YColor',...
    [0 0 0],'YGrid','on','ZColor',[0 0 0]);
